# Servidor
server.port=8081

# Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ticket_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true


# Seguridad JWT
# Usamos todos la misma para que no haya errores de validación entre nosotros
jwt.secret=bWlfY2xhdmVfc3VwZXJfc2VjcmV0YV9wYXJhX2p3dF8yMDI2X3RpY2tldGZsb3c=
# Tiempo de expiración del token (en milisegundos)
# 86400000 ms = 24 horas
jwt.expiration=86400000


# prueba
logging.level.org.springframework.security=DEBUG