#Servidor
server.port= 8081

# Base de Datos PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ticketflow}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Seguridad JWT
jwt.secret=bWlfY2xhdmVfc3VwZXJfc2VjcmV0YV9wYXJhX2p3dF8yMDI2X3RpY2tldGZsb3c=
jwt.expiration=86400000

# Logs de depuracion
logging.level.org.springframework.security=INFO
